// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    'Fa:angleDoubleLeft': typeof import('virtual:vite-icons/fa/angle-double-left')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MainCard: typeof import('./src/components/MainCard.vue')['default']
    'Mdi:twitter': typeof import('virtual:vite-icons/mdi/twitter')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
